### ISSUE TITLE
WRFV4.4 runs unstable with openmpi

### ISSUE THREAD

**Issue by SettRaziel** [SettRaziel/wrf_archlinux#126]
Switching to WRFV4.4 on my production machine introduced some unstable behavior of the model run in regard to MPI. Changing from self compiled mpich to openmpi archlinux package most of the model runs fail with a segmentation fault:
```
Program received signal SIGSEGV: Segmentation fault - invalid memory reference.

Backtrace for this error:
#0  0x7f4d54af2f4f in ???
#1  0x560856792c14 in ???
#2  0x5608567b5eca in ???
#3  0x5608567c59d8 in ???
#4  0x560855dc3a3b in ???
#5  0x7f4d54d07475 in gomp_thread_start
        at /usr/src/debug/gcc/gcc/libgomp/team.c:129
#6  0x7f4d54b3fbb4 in ???
#7  0x7f4d54bc1d8f in ???
#8  0xffffffffffffffff in ???
```
Switching back to WRFV4.2 with mpich v3.3 seems to solve the problem. ArchLinux has a package for mpich, but it is outdated and fails to compile. It needs to be checked how to install the mpich packages from ArchLinux or to check if a self compiled version of mpich resolves this issue.

**Comment by SettRaziel** [comment]
Return to mpich v4.1.1 as parallelization library, done with #128.
